# docker-compose.yml
# This file defines the Docker services and configurations for the application environment.
# It includes a PostgreSQL service with defined environment variables and persistent volume configuration.
# Docker Compose orchestrates the services, making it easy to start up the entire environment with a single command.

services:           
  postgres:
    image: postgres:latest       
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: test
    ports:
      - "6543:5432"     
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:                      
