version: '3'
services:
  # app:
  #   build: .                # Build the FastAPI app container from the Dockerfile
  #   ports:
  #     - "8000:8000"          # Expose FastAPI app on port 8000
  #   depends_on:
  #     - postgres             # Ensure PostgreSQL starts before FastAPI
  postgres:
    image: postgres:13       # Use the official PostgreSQL image
    environment:
      POSTGRES_USER: admin  # Set environment variables for PostgreSQL
      POSTGRES_PASSWORD: adminbe
      POSTGRES_DB: test
    ports:
      - "5432:5432"          # Expose PostgreSQL on port 5432
#     volumes:
#       - pgdata:/var/lib/postgresql/data  # Persist database data

# volumes:
#   pgdata:                      # Define a volume for PostgreSQL data persistence
