services:
  # app:
  #   build: .                
  #   ports:
  #     - "8000:8000"          
  #   depends_on:
  #     - postgres             
  postgres:
    image: postgres:latest       
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"     
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:                      
